sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t yakovlev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yakovlev/docker-react npm run test